name: Fetch packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy3.8' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: cd ${GITHUB_WORKSPACE}/packagist-fetcher  &&  pip install -r requirements.txt
      - name: Fetch packages
        run: cd ${GITHUB_WORKSPACE}/packagist-fetcher  && python main.py
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Update packages list"
