name: Fetch packages
on:
  workflow_dispatch:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy3.8' ]
      name: Python ${{ matrix.python-version }}
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
        - run:|
          cd /packagist-fetcher/
          pip install -r requirements.txt
          python main.py